package com.osrapi.models.csr;

import java.util.ArrayList;
import java.util.List;
import java.util.Map;

import javax.persistence.CollectionTable;
import javax.persistence.Column;
import javax.persistence.ElementCollection;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Inheritance;
import javax.persistence.InheritanceType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToOne;
import javax.persistence.MapKeyColumn;
import javax.persistence.MapKeyJoinColumn;
import javax.persistence.MappedSuperclass;
import javax.persistence.OneToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;

import org.hibernate.annotations.Cascade;
import org.hibernate.annotations.CascadeType;
import org.hibernate.annotations.Fetch;
import org.hibernate.annotations.FetchMode;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * @author drau
 */
@JsonInclude(JsonInclude.Include.NON_EMPTY)
@Entity
@Table(name = "father_vocation", schema = "csr")
public final class CSRFatherVocationEntity {
    /**
     * the primary key - an autogenerated id (unique for each user in the db).
     */
    @Id
    @Column(name = "father_vocation_id")
    @GeneratedValue(strategy = GenerationType.SEQUENCE,
  generator = "father_vocation_seq")
    @SequenceGenerator(
        name = "father_vocation_seq",
        sequenceName = "csr.father_vocation_id_seq",
        allocationSize = 1
    )
    private Long                    id;
    /** Creates a new instance of {@link CSRFatherVocationEntity}. */
    public CSRFatherVocationEntity() {
        super();
    }
    /**
     * Gets the id.
     * @return {@link Long}
     */
    public Long getId() {
        return id;
    }
    /**
     * Sets the id.
     * @param val the new value
     */
    public void setId(final Long val) {
        id = val;
    }

    /** the rollMax. */
    @Column(name = "roll_max")
    @JsonProperty("roll_max")
    @NotNull
    private long                    rollMax;
    /**
     * Gets the rollMax.
     * @return {@link long}
     */
    public long getRollMax() {
        return rollMax;
    }
    /**
     * Sets the rollMax.
     * @param val the new value
     */
    public void setRollMax(final long val) {
        rollMax = val;
    }

    /** the rollMin. */
    @Column(name = "roll_min")
    @JsonProperty("roll_min")
    @NotNull
    private long                    rollMin;
    /**
     * Gets the rollMin.
     * @return {@link long}
     */
    public long getRollMin() {
        return rollMin;
    }
    /**
     * Sets the rollMin.
     * @param val the new value
     */
    public void setRollMin(final long val) {
        rollMin = val;
    }

    /** the numStartingBonusSkills. */
    @Column(name = "num_starting_bonus_skills")
    @JsonProperty("num_starting_bonus_skills")
    
    private Long                    numStartingBonusSkills;
    /**
     * Gets the numStartingBonusSkills.
     * @return {@link Long}
     */
    public Long getNumStartingBonusSkills() {
        return numStartingBonusSkills;
    }
    /**
     * Sets the numStartingBonusSkills.
     * @param val the new value
     */
    public void setNumStartingBonusSkills(final Long val) {
        numStartingBonusSkills = val;
    }

    /** the numStartingAgriculturalSkills. */
    @Column(name = "num_starting_agricultural_skills")
    @JsonProperty("num_starting_agricultural_skills")
    
    private Long                    numStartingAgriculturalSkills;
    /**
     * Gets the numStartingAgriculturalSkills.
     * @return {@link Long}
     */
    public Long getNumStartingAgriculturalSkills() {
        return numStartingAgriculturalSkills;
    }
    /**
     * Sets the numStartingAgriculturalSkills.
     * @param val the new value
     */
    public void setNumStartingAgriculturalSkills(final Long val) {
        numStartingAgriculturalSkills = val;
    }

    /** the socialStatus. */
    @Column(name = "social_status")
    @JsonProperty("social_status")
    @NotNull
    private long                    socialStatus;
    /**
     * Gets the socialStatus.
     * @return {@link long}
     */
    public long getSocialStatus() {
        return socialStatus;
    }
    /**
     * Sets the socialStatus.
     * @param val the new value
     */
    public void setSocialStatus(final long val) {
        socialStatus = val;
    }

    /** the name. */
    @Column(name = "name")
    @JsonProperty("name")
    @NotNull
    private String                    name;
    /**
     * Gets the name.
     * @return {@link String}
     */
    public String getName() {
        return name;
    }
    /**
     * Sets the name.
     * @param val the new value
     */
    public void setName(final String val) {
        name = val;
    }

    /** the socialClass. */
    @ManyToOne(targetEntity = CSRSocialClassEntity.class, fetch = FetchType.EAGER)
    @Fetch(FetchMode.SELECT)
    @JoinColumn(name = "socialClass")
    @JsonProperty("social_class")
  @NotNull
    private CSRSocialClassEntity    socialClass;
    /**
     * Gets the socialClass.
     * @return {@link CSRSocialClassEntity}
     */
    public CSRSocialClassEntity getSocialClass() {
        return socialClass;
    }
    /**
     * Sets the socialClass.
     * @param val the new value
     */
    public void setSocialClass(final CSRSocialClassEntity val) {
        socialClass = val;
    }

    /**
     * the list of {@link CSRSkillEntity}s associated with this
     * {@link CSRFatherVocationEntity}.
     */
    @OneToMany(targetEntity = CSRSkillEntity.class,
      fetch = FetchType.EAGER)
    @Fetch(FetchMode.SELECT)
    @JoinTable(name = "father_vocation_starting_skills_lookup", schema = "csr",
  joinColumns = @JoinColumn(name = "father_vocation_id",
  referencedColumnName = "father_vocation_id"),
  inverseJoinColumns = @JoinColumn(name = "skill_id",
  referencedColumnName = "skill_id"))
    @JsonProperty("starting_skills")
    private List<CSRSkillEntity>    startingSkills;
    /**
     * Gets the list of startingSkillss.
     * @return {@link List}<{@link CSRSkillEntity}>
     */
    public List<CSRSkillEntity> getStartingSkills() {
        return startingSkills;
    }
    /**
     * Sets the list of startingSkillss.
     * @param val the new value
     */
    public void setStartingSkills(final List<CSRSkillEntity> val) {
        startingSkills = val;
    }

}

