package com.osrapi.models.ll;

import java.util.ArrayList;
import java.util.List;
import java.util.Map;

import javax.persistence.CollectionTable;
import javax.persistence.Column;
import javax.persistence.ElementCollection;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Inheritance;
import javax.persistence.InheritanceType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToOne;
import javax.persistence.MapKeyColumn;
import javax.persistence.MapKeyJoinColumn;
import javax.persistence.MappedSuperclass;
import javax.persistence.OneToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;

import org.hibernate.annotations.Cascade;
import org.hibernate.annotations.CascadeType;
import org.hibernate.annotations.Fetch;
import org.hibernate.annotations.FetchMode;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * @author drau
 */
@JsonInclude(JsonInclude.Include.NON_EMPTY)
@Entity
@Table(name = "script_bundle", schema = "ll")
public final class LLScriptBundleEntity {
    /**
     * the primary key - an autogenerated id (unique for each user in the db).
     */
    @Id
    @Column(name = "script_bundle_id")
    @GeneratedValue(strategy = GenerationType.SEQUENCE,
  generator = "script_bundle_seq")
    @SequenceGenerator(
        name = "script_bundle_seq",
        sequenceName = "ll.script_bundle_id_seq",
        allocationSize = 1
    )
    private Long                    id;
    /** Creates a new instance of {@link LLScriptBundleEntity}. */
    public LLScriptBundleEntity() {
        super();
    }
    /**
     * Gets the id.
     * @return {@link Long}
     */
    public Long getId() {
        return id;
    }
    /**
     * Sets the id.
     * @param val the new value
     */
    public void setId(final Long val) {
        id = val;
    }

    /** the name. */
    @Column(name = "name")
    @JsonProperty("name")
    @NotNull
    private String                    name;
    /**
     * Gets the name.
     * @return {@link String}
     */
    public String getName() {
        return name;
    }
    /**
     * Sets the name.
     * @param val the new value
     */
    public void setName(final String val) {
        name = val;
    }

    /**
     * the list of {@link LLScriptActionEntity}s associated with this
     * {@link LLScriptBundleEntity}.
     */
    @OneToMany(targetEntity = LLScriptActionEntity.class,
      fetch = FetchType.EAGER)
    @Fetch(FetchMode.SELECT)
    @JoinTable(name = "script_bundle_scripts_lookup", schema = "ll",
  joinColumns = @JoinColumn(name = "script_bundle_id",
  referencedColumnName = "script_bundle_id"),
  inverseJoinColumns = @JoinColumn(name = "script_action_id",
  referencedColumnName = "script_action_id"))
    @JsonProperty("scripts")
    private List<LLScriptActionEntity>    scripts;
    /**
     * Gets the list of scriptss.
     * @return {@link List}<{@link LLScriptActionEntity}>
     */
    public List<LLScriptActionEntity> getScripts() {
        return scripts;
    }
    /**
     * Sets the list of scriptss.
     * @param val the new value
     */
    public void setScripts(final List<LLScriptActionEntity> val) {
        scripts = val;
    }

}

