[{
	"name": "BLUNT_WEAPON"
}, {
	"name": "CHAOTIC"
}, {
	"name": "CLERIC"
}, {
	"name": "HEAVY_CROSSBOW_AMMUNITION"
}, {
	"name": "LIGHT_CROSSBOW_AMMUNITION"
}, {
	"name": "DWARF"
}, {
	"name": "EDGED_WEAPON"
}, {
	"name": "ELF"
}, {
	"name": "FIGHTER"
}, {
	"name": "HALFLING"
}, {
	"name": "HEAVY_ARMOUR"
}, {
	"name": "HEAVY_WEAPON"
}, {
	"name": "HUMAN"
}, {
	"name": "LAWFUL"
}, {
	"name": "LIGHT_WEAPON"
}, {
	"name": "LONGBOW"
}, {
	"name": "LONGBOW_AMMUNITION"
}, {
	"name": "MAGE"
}, {
	"name": "NEUTRAL"
}, {
	"name": "PIERCING_WEAPON"
}, {
	"name": "PROJECTILE_WEAPON"
}, {
	"name": "SILVER_WEAPON"
}, {
	"name": "SHORTBOW_AMMUNITION"
}, {
	"name": "SLING_AMMUNITION"
}, {
	"name": "STAFF"
}, {
	"name": "THIEF"
}, {
	"name": "THROWN_WEAPON"
}]