package com.osrapi.models.tft;

import java.util.ArrayList;
import java.util.List;
import java.util.Map;

import javax.persistence.CollectionTable;
import javax.persistence.Column;
import javax.persistence.ElementCollection;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Inheritance;
import javax.persistence.InheritanceType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToOne;
import javax.persistence.MapKeyColumn;
import javax.persistence.MapKeyJoinColumn;
import javax.persistence.MappedSuperclass;
import javax.persistence.OneToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;

import org.hibernate.annotations.Cascade;
import org.hibernate.annotations.CascadeType;
import org.hibernate.annotations.Fetch;
import org.hibernate.annotations.FetchMode;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * @author drau
 */
@JsonInclude(JsonInclude.Include.NON_EMPTY)
@Entity
@Table(name = "gender", schema = "tft")
public final class TFTGenderEntity {
    /**
     * the primary key - an autogenerated id (unique for each user in the db).
     */
    @Id
    @Column(name = "gender_id")
    @GeneratedValue(strategy = GenerationType.SEQUENCE,
  generator = "gender_seq")
    @SequenceGenerator(
        name = "gender_seq",
        sequenceName = "tft.gender_id_seq",
        allocationSize = 1
    )
    private Long                    id;
    /** Creates a new instance of {@link TFTGenderEntity}. */
    public TFTGenderEntity() {
        super();
    }
    /**
     * Gets the id.
     * @return {@link Long}
     */
    public Long getId() {
        return id;
    }
    /**
     * Sets the id.
     * @param val the new value
     */
    public void setId(final Long val) {
        id = val;
    }

    /** the genderParent. */
    @Column(name = "gender_parent")
    @JsonProperty("gender_parent")
    @NotNull
    private String                    genderParent;
    /**
     * Gets the genderParent.
     * @return {@link String}
     */
    public String getGenderParent() {
        return genderParent;
    }
    /**
     * Sets the genderParent.
     * @param val the new value
     */
    public void setGenderParent(final String val) {
        genderParent = val;
    }

    /** the genderOffspring. */
    @Column(name = "gender_offspring")
    @JsonProperty("gender_offspring")
    @NotNull
    private String                    genderOffspring;
    /**
     * Gets the genderOffspring.
     * @return {@link String}
     */
    public String getGenderOffspring() {
        return genderOffspring;
    }
    /**
     * Sets the genderOffspring.
     * @param val the new value
     */
    public void setGenderOffspring(final String val) {
        genderOffspring = val;
    }

    /** the reflexive. */
    @Column(name = "reflexive")
    @JsonProperty("reflexive")
    @NotNull
    private String                    reflexive;
    /**
     * Gets the reflexive.
     * @return {@link String}
     */
    public String getReflexive() {
        return reflexive;
    }
    /**
     * Sets the reflexive.
     * @param val the new value
     */
    public void setReflexive(final String val) {
        reflexive = val;
    }

    /** the independentPossessive. */
    @Column(name = "independent_possessive")
    @JsonProperty("independent_possessive")
    @NotNull
    private String                    independentPossessive;
    /**
     * Gets the independentPossessive.
     * @return {@link String}
     */
    public String getIndependentPossessive() {
        return independentPossessive;
    }
    /**
     * Sets the independentPossessive.
     * @param val the new value
     */
    public void setIndependentPossessive(final String val) {
        independentPossessive = val;
    }

    /** the dependentPossessive. */
    @Column(name = "dependent_possessive")
    @JsonProperty("dependent_possessive")
    @NotNull
    private String                    dependentPossessive;
    /**
     * Gets the dependentPossessive.
     * @return {@link String}
     */
    public String getDependentPossessive() {
        return dependentPossessive;
    }
    /**
     * Sets the dependentPossessive.
     * @param val the new value
     */
    public void setDependentPossessive(final String val) {
        dependentPossessive = val;
    }

    /** the objective. */
    @Column(name = "objective")
    @JsonProperty("objective")
    @NotNull
    private String                    objective;
    /**
     * Gets the objective.
     * @return {@link String}
     */
    public String getObjective() {
        return objective;
    }
    /**
     * Sets the objective.
     * @param val the new value
     */
    public void setObjective(final String val) {
        objective = val;
    }

    /** the subjective. */
    @Column(name = "subjective")
    @JsonProperty("subjective")
    @NotNull
    private String                    subjective;
    /**
     * Gets the subjective.
     * @return {@link String}
     */
    public String getSubjective() {
        return subjective;
    }
    /**
     * Sets the subjective.
     * @param val the new value
     */
    public void setSubjective(final String val) {
        subjective = val;
    }

    /** the name. */
    @Column(name = "name")
    @JsonProperty("name")
    @NotNull
    private String                    name;
    /**
     * Gets the name.
     * @return {@link String}
     */
    public String getName() {
        return name;
    }
    /**
     * Sets the name.
     * @param val the new value
     */
    public void setName(final String val) {
        name = val;
    }

    /** the description. */
    @Column(name = "description")
    @JsonProperty("description")
    @NotNull
    private String                    description;
    /**
     * Gets the description.
     * @return {@link String}
     */
    public String getDescription() {
        return description;
    }
    /**
     * Sets the description.
     * @param val the new value
     */
    public void setDescription(final String val) {
        description = val;
    }

}

