[{
	"code": "MINUS_1",
	"percent": false,
	"value": -1
}, {
	"code": "MINUS_2",
	"percent": false,
	"value": -2
}, {
	"code": "MINUS_3",
	"percent": false,
	"value": -3
}, {
	"code": "MINUS_4",
	"percent": false,
	"value": -4
}, {
	"code": "MINUS_5",
	"percent": false,
	"value": -5
}, {
	"code": "MINUS_6",
	"percent": false,
	"value": -6
}, {
	"code": "PLUS_2",
	"percent": false,
	"value": 2
}]