  [{
    "type": "CREATE_EXIT",
    "name": "CREATE_EXIT_278_343",
    "destination": "343",
    "direction": "EAST",
    "origin": "278"
  }, {
    "type": "DMG_PLAYER",
    "name": "DMG_PLAYER_ST_1",
    "attribute": "ST",
    "amount": 1
  }, {
    "type": "MOVE_PLAYER",
    "name": "MOVE_PLAYER_343",
    "room_code": "343"
  }, {
    "type": "PERMALOCK",
    "name": "PERMALOCK_278",
    "door_name": "278_DOOR"
  }, {
    "type": "SET_ROOM_TEXT",
    "name": "278_POST_BASH_FAILURE",
    "text_name": "278_POST_BASH_FAILURE"
  }, {
    "type": "SET_ROOM_TEXT",
    "name": "278_POST_BASH_SUCCESS",
    "text_name": "278_POST_BASH_SUCCESS"
  }, {
    "type": "SHOW_TEXT",
    "name": "278_BASH_FAILURE",
    "error": true,
    "text_name": "278_BASH_SUCCESS"
  }, {
    "type": "SHOW_TEXT",
    "name": "278_BASH_SUCCESS",
    "error": false,
    "text_name": "278_BASH_SUCCESS"
  }, {
    "type": "SPAWN_MOB",
    "name": "SPAWN_ORC1",
    "mob_code": "ORC1"
  }, {
    "type": "TEST_YOUR_LUCK",
    "pass_scripts": "71_PASS_LUCK",
    "fail_scripts": "71_FAIL_LUCK"
  }]