package com.osrapi.models.avalon;

import java.util.ArrayList;
import java.util.List;
import java.util.Map;

import javax.persistence.CollectionTable;
import javax.persistence.Column;
import javax.persistence.ElementCollection;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Inheritance;
import javax.persistence.InheritanceType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToOne;
import javax.persistence.MapKeyColumn;
import javax.persistence.MapKeyJoinColumn;
import javax.persistence.MappedSuperclass;
import javax.persistence.OneToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;

import org.hibernate.annotations.Cascade;
import org.hibernate.annotations.CascadeType;
import org.hibernate.annotations.Fetch;
import org.hibernate.annotations.FetchMode;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * @author drau
 */
@JsonInclude(JsonInclude.Include.NON_EMPTY)
@Entity
@Table(name = "magic_color", schema = "avalon")
public final class AVALONMagicColorEntity {
    /**
     * the primary key - an autogenerated id (unique for each user in the db).
     */
    @Id
    @Column(name = "magic_color_id")
    @GeneratedValue(strategy = GenerationType.SEQUENCE,
  generator = "magic_color_seq")
    @SequenceGenerator(
        name = "magic_color_seq",
        sequenceName = "avalon.magic_color_id_seq",
        allocationSize = 1
    )
    private Long                    id;
    /** Creates a new instance of {@link AVALONMagicColorEntity}. */
    public AVALONMagicColorEntity() {
        super();
    }
    /**
     * Gets the id.
     * @return {@link Long}
     */
    public Long getId() {
        return id;
    }
    /**
     * Sets the id.
     * @param val the new value
     */
    public void setId(final Long val) {
        id = val;
    }

    /** the shortName. */
    @Column(name = "short_name")
    @JsonProperty("short_name")
    @NotNull
    private String                    shortName;
    /**
     * Gets the shortName.
     * @return {@link String}
     */
    public String getShortName() {
        return shortName;
    }
    /**
     * Sets the shortName.
     * @param val the new value
     */
    public void setShortName(final String val) {
        shortName = val;
    }

    /** the longName. */
    @Column(name = "long_name")
    @JsonProperty("long_name")
    @NotNull
    private String                    longName;
    /**
     * Gets the longName.
     * @return {@link String}
     */
    public String getLongName() {
        return longName;
    }
    /**
     * Sets the longName.
     * @param val the new value
     */
    public void setLongName(final String val) {
        longName = val;
    }

}

