  [{
    "flag": 1,
    "name": "DAMAGE_TYPE_ACID"
  }, {
    "flag": 2,
    "name": "DAMAGE_TYPE_COLD"
  }, {
    "flag": 4,
    "name": "DAMAGE_TYPE_DRAIN_LIFE"
  }, {
    "flag": 8,
    "name": "DAMAGE_TYPE_DRAIN_MANA"
  }, {
    "flag": 16,
    "name": "DAMAGE_TYPE_FAKEFIRE"
  }, {
    "flag": 32,
    "name": "DAMAGE_TYPE_FIELD"
  }, {
    "flag": 64,
    "name": "DAMAGE_TYPE_FIRE"
  }, {
    "flag": 128,
    "name": "DAMAGE_TYPE_GAS"
  }, {
    "flag": 0,
    "name": "DAMAGE_TYPE_GENERIC"
  }, {
    "flag": 256,
    "name": "DAMAGE_TYPE_LIGHTNING"
  }, {
    "flag": 512,
    "name": "DAMAGE_TYPE_MAGICAL"
  }, {
    "flag": 1024,
    "name": "DAMAGE_TYPE_METAL"
  }, {
    "flag": 2048,
    "name": "DAMAGE_TYPE_NO_FIX"
  }, {
    "flag": 4096,
    "name": "DAMAGE_TYPE_ORGANIC"
  }, {
    "flag": 8192,
    "name": "DAMAGE_TYPE_PER_SECOND"
  }, {
    "flag": 16384,
    "name": "DAMAGE_TYPE_POISON"
  }, {
    "flag": 32768,
    "name": "DAMAGE_TYPE_PUSH"
  }, {
    "flag": 65536,
    "name": "DAMAGE_TYPE_STONE"
  }, {
    "flag": 131072,
    "name": "DAMAGE_TYPE_WOOD"
  }]