  [{
    "code": "d1",
    "value": 1
  }, {
    "code": "d2",
    "value": 2
  }, {
    "code": "d3",
    "value": 3
  }, {
    "code": "d4",
    "value": 4
  }, {
    "code": "d6",
    "value": 6
  }, {
    "code": "d8",
    "value": 8
  }, {
    "code": "d10",
    "value": 10
  }, {
    "code": "d12",
    "value": 12
  }, {
    "code": "d20",
    "value": 20
  }, {
    "code": "d100",
    "value": 100
  }]