package com.osrapi.models.ff;

import java.util.ArrayList;
import java.util.List;
import java.util.Map;

import javax.persistence.CollectionTable;
import javax.persistence.Column;
import javax.persistence.ElementCollection;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Inheritance;
import javax.persistence.InheritanceType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToOne;
import javax.persistence.MapKeyColumn;
import javax.persistence.MapKeyJoinColumn;
import javax.persistence.MappedSuperclass;
import javax.persistence.OneToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;

import org.hibernate.annotations.Cascade;
import org.hibernate.annotations.CascadeType;
import org.hibernate.annotations.Fetch;
import org.hibernate.annotations.FetchMode;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * @author drau
 */
@JsonInclude(JsonInclude.Include.NON_EMPTY)
@Entity
@Table(name = "map_cell", schema = "ff")
public final class FFMapCellEntity {
    /**
     * the primary key - an autogenerated id (unique for each user in the db).
     */
    @Id
    @Column(name = "map_cell_id")
    @GeneratedValue(strategy = GenerationType.SEQUENCE,
  generator = "map_cell_seq")
    @SequenceGenerator(
        name = "map_cell_seq",
        sequenceName = "ff.map_cell_id_seq",
        allocationSize = 1
    )
    private Long                    id;
    /** Creates a new instance of {@link FFMapCellEntity}. */
    public FFMapCellEntity() {
        super();
    }
    /**
     * Gets the id.
     * @return {@link Long}
     */
    public Long getId() {
        return id;
    }
    /**
     * Sets the id.
     * @param val the new value
     */
    public void setId(final Long val) {
        id = val;
    }

    /** the tile. */
    @ManyToOne(targetEntity = FFMapTileEntity.class, fetch = FetchType.EAGER)
    @Fetch(FetchMode.SELECT)
    @JoinColumn(name = "tile")
    @JsonProperty("map_tile")
  @NotNull
    private FFMapTileEntity    tile;
    /**
     * Gets the tile.
     * @return {@link FFMapTileEntity}
     */
    public FFMapTileEntity getTile() {
        return tile;
    }
    /**
     * Sets the tile.
     * @param val the new value
     */
    public void setTile(final FFMapTileEntity val) {
        tile = val;
    }

    /** the y. */
    @Column(name = "y")
    @JsonProperty("y")
    @NotNull
    private long                    y;
    /**
     * Gets the y.
     * @return {@link long}
     */
    public long getY() {
        return y;
    }
    /**
     * Sets the y.
     * @param val the new value
     */
    public void setY(final long val) {
        y = val;
    }

    /** the x. */
    @Column(name = "x")
    @JsonProperty("x")
    @NotNull
    private long                    x;
    /**
     * Gets the x.
     * @return {@link long}
     */
    public long getX() {
        return x;
    }
    /**
     * Sets the x.
     * @param val the new value
     */
    public void setX(final long val) {
        x = val;
    }

    /** the name. */
    @Column(name = "name")
    @JsonProperty("name")
    @NotNull
    private String                    name;
    /**
     * Gets the name.
     * @return {@link String}
     */
    public String getName() {
        return name;
    }
    /**
     * Sets the name.
     * @param val the new value
     */
    public void setName(final String val) {
        name = val;
    }

}

