  [{
    "code": 0,
    "name": "Cavalry"
  }, {
    "code": 1,
    "name": "Crossbow"
  }, {
    "code": 2,
    "name": "Engineer"
  }, {
    "code": 3,
    "name": "Entangling"
  }, {
    "code": 4,
    "name": "Explosive"
  }, {
    "code": 5,
    "name": "Fencing"
  }, {
    "code": 6,
    "name": "Flail"
  }, {
    "code": 7,
    "name": "Gunpowder"
  }, {
    "code": 8,
    "name": "Longbow"
  }, {
    "code": 9,
    "name": "Ordinary"
  }, {
    "code": 10,
    "name": "Parrying"
  }, {
    "code": 11,
    "name": "Sling"
  }, {
    "code": 12,
    "name": "Throwing"
  }, {
    "code": 13,
    "name": "Two-handed"
  }]